# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_report_usermadegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_investor_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_site_manager',
            field=models.BooleanField(default=False),
        ),
    ]
