# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171106_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('can_add_report', 'Can add report'), ('can_delete_report', 'Can delete report'))},
        ),
    ]
