# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171113_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('can_view_reports', 'Can view reports'), ('can_change_reports', 'Can change reports'))},
        ),
    ]
