# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171112_2050'),
        ('app', '0006_auto_20171113_2203'),
    ]

    operations = [
    ]
