# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='app.ReportFile'),
        ),
    ]
