# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171119_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
