# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171120_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='files',
            field=models.ManyToManyField(blank=True, to='app.ReportFile'),
        ),
    ]
