# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171119_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='files',
        ),
        migrations.AddField(
            model_name='report',
            name='files',
            field=models.ManyToManyField(null=True, to='app.ReportFile'),
        ),
    ]
