# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171119_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='timeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
