# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171126_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
