# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171126_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='companyCEO',
            field=models.CharField(default='CEO1', max_length=50),
            preserve_default=False,
        ),
    ]
