# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_report_companyceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='currentProjects',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
