# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_report_currentprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='companyEmail',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='currentProjects',
            field=models.CharField(max_length=200),
        ),
    ]
