# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20171126_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
