# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_message_text',
            field=models.TextField(default=''),
        ),
    ]
