# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_remove_report_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='starred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='companyUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
