# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_message_encrypted_message_text'),
        ('app', '0020_auto_20171201_2025'),
    ]

    operations = [
    ]
