# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20171202_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='should_display_unencrypted_message_text',
            field=models.BooleanField(default=False),
        ),
    ]
