# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_message_should_display_unencrypted_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
