# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20171202_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time_stamp']},
        ),
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
