# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20171203_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermadegroup',
            name='reports',
            field=models.ManyToManyField(to='app.Report'),
        ),
    ]
