# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_usermadegroup_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='key',
            field=models.BinaryField(default=b''),
        ),
    ]
