# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_key_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='key',
        ),
    ]
