# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_key_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='comments',
            field=models.ManyToManyField(blank=True, to='app.Comment'),
        ),
    ]
