# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_report_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
